print('Здравствуйте')
print('Ответьте, пожалуйта, на следующие вопросы для составления анкеты')
print('Ваше имя')
name = input()
print('Ваша фамилия')
surname = input()
print('Ваше отчество')
lastname = input()
print('Ваш возраст')
age = int(input())
print('Ваш пол')
sex = input()
print('Ваше хобби')
hobby = input()
print('Ваш город')
city = input()
print('Какое у вас домашнее животное')
pet = input()
print('Спасибо за ответы')
print('АНКЕТА')
print('ФИО:', surname, name, lastname)
print('Возраст:', age)
print('Пол:', sex)
print('Хобби:', hobby)
print('Город:', city)
print('Домашнее животное:', pet)
