print('Введите коэффициенты системы уравнений вида')
print('ax+cy=d')
print('by-kx=ac')
print('a=')
a = float(input())
print('b=')
b = float(input())
print('c=')
c = float(input())
print('d=')
d = float(input())
print('k=')
k = float(input())
if a == 0:
    print('Введите другие коэффициенты')
else:
    y = (k*d+(a**2)*c)/(k*c+a*b)
    x = (d-c*y)/a
    print('Корнями системы уравнения')
    print(a, 'x+', c, 'y=', d)
    print(b, 'y-', k, 'x=', a, '*', c)
    print('являются')
    print('x=', x)
    print('y=', y)
